version: '3.3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: decher/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/media
      - ./data/:/data_backend
  frontend:
    image: decher/foodgram_frontend
    env_file: .env
    volumes:
      - static_volume:/app/result_build
  gateway:
    image: nginx:1.19.3
    env_file: .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docs/:/static/api/docs/
      - static_volume:/static
      - media_volume:/media
    ports:
      - 7000:80
    depends_on:
      - backend