# Generated by Django 4.2.4 on 2023-08-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_favorite_alter_recipe_shoppingcart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientinrecipe',
            options={'ordering': ('-id',), 'verbose_name': 'Ингрединт к рецепту', 'verbose_name_plural': 'Ингрединты к рецепту'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.tag', verbose_name='Тэги'),
        ),
    ]
